Release v24.12.6

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,6 +11,21 @@ jobs:
     runs-on: windows-latest
 
     steps:
+    - name: Test timestamp server
+      shell: pwsh
+      run: |
+        try {
+          $response = Invoke-WebRequest -Uri "https://ca.signfiles.com/tsa/get.aspx" -Method Head
+          if ($response.StatusCode -ne 200) {
+            Write-Error "Timestamp server is not reachable. Status code: $($response.StatusCode)"
+            exit 1
+          }
+          Write-Output "Timestamp server is reachable."
+        } catch {
+          Write-Error "Timestamp server test failed."
+          exit 1
+        }
+
     - name: Checkout code
       uses: actions/checkout@v4
       with:
@@ -65,7 +80,7 @@ jobs:
     - name: Sign executable
       run: |
         $path = '${{ steps.find-signtool.outputs.signtool_path }}'
-        & "$path" sign /f meinzertifikat.pfx /p ${{ secrets.CERTIFICATE_PASSWORD }} /fd SHA256 /t http://timestamp.entrust.net/TSS/RFC3161sha2TS ./publish/BiMaDockSetup.exe
+        & "$path" sign /f meinzertifikat.pfx /p ${{ secrets.CERTIFICATE_PASSWORD }} /fd SHA256 /t https://ca.signfiles.com/tsa/get.aspx ./publish/BiMaDockSetup.exe
 
     - name: Determine tag
       id: determine_tag
